language: java
jdk:
  - oraclejdk8

branches:
  only:
    - master

before_install:
  - pip install --user codecov

script:
  - mvn clean compile test-compile resources:resources resources:testResources surefire:test

after_success:
  - codecov
